accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
  path('signup',views.signup_view,name='signup'),

  path('login',views.login_view,name= 'login'),

  path('logout',views.logout_view,name='logout')

]

articles/urls.py
from django.urls import path
from .import views

app_name="articles"
urlpatterns=[

path('',views.articles_list,name="list"),
path('create',views.create_article,name= "create"),


path('<slug>',views.articles_detail,name="detail"),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('mjs/',views.mjs),
    path('',views.home),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
     title = models.CharField(max_length=100)
     slug= models.SlugField()
     body = models.TextField()
     date = models.DateTimeField(auto_now_add=True)
     image = models.ImageField(default='default.jpg',blank=True)

     def __str__(self):
         return self.title

     def snippet(self):
         return self.body[:50]+ '  ...   '

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form =UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)

            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form= AuthenticationForm(data=request.POST)
        if form.is_valid():

            user = form.get_user()

            login(request,user)


            return redirect('articles:list')
    else:
        form= AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)

        return redirect('articles:list')

articles/views.py
from django.shortcuts import render , HttpResponse
from .import models
from django.contrib.auth.decorators import login_required


# Create your views here.
def articles_list(request):
    articles = models.Article.objects.all().order_by('-date')
    return render(request,'articles/articleslist.html',{'articles':articles})


def articles_detail(request,slug):
    # return HttpResponse(slug)
    article=models.Article.objects.get(slug=slug)
    return render(request,'articles/articles_detail.html',{'article':article})


@login_required(login_url ="/accounts/login")
def create_article(request):
    return render(request,'articles/create_article.html')

djangoBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    #return HttpResponse('love programmer very very very very match')
    return render(request,'about.html')

def mjs(request):
    return HttpResponse('me is good boy')

def home(request):
    #return HttpResponse('home')
    return render(request,'Home.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{%block content%}
<h1>login</h1>

<form class="" action="{%url 'accounts:login' %}" method="post">
  {{form}}
  {%  csrf_token %}

  <input type="submit"  value="login">
</form>
{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{%block content%}
<h1>sign up</h1>

<form class="site-form" action="{%url 'accounts:signup'%}" method="post">
  {{form}}
  {%  csrf_token %}

  <input type="submit"  value="signup">
</form>
{%endblock%}

articles/templates/articles/articles_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="article_detail">
  <div class="article">
    <img src="{{article.image.url}}" alt="">
    <h1>{{article.title}}</h1>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>

</div>

{% endblock %}

articles/templates/articles/articleslist.html
{%extends 'base.html'  %}
{%block title%}
articles
{%endblock%}

 {%block content%}

<div class="container">
  <h1>articleslist</h1>
  {% for article in articles%}
  <h2><a href="{%url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
  <p>{{article.snippet}}</p>
  <p>{{article.date}}</p>
  {% endfor %}
</div>
{%endblock%}

articles/templates/articles/create_article.html
{% extends 'base.html'%}

{%block content%}
<div class="create_article">

  <h2>
    creat articles
  </h2>

</div>

{%endblock%}

templates/Home.html
{%load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home</title>
  
  </head>
  <body>
    <h1>home</h1>
    <p>welcome to my blog</p>
  </body>
</html>

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>about</title>
  </head>
  <body>
    <h1>aboout</h1>
    <p>محمد عاشق جنگو هست</p>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
    {%block title%}
   Article
     {%endblock%}
      </title>
    <link rel="stylesheet" href="{%static 'styles.css' %}">
  </head>
  <body>
    <h2><a href="{% url 'articles:list%'} ">LOGO</a></h2>

      <nav>
        <ul>
          <li>
            <form class="logout_link " action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}

              <button type="submit" >logout</button>

            </form>

          </li>
        </ul>


      </nav>



    <div class="wrapper">
     {%block content%}

     {%endblock%}
     </div>
  </body>
</html>